[package]
name = "rt-metainfo"
description = "TorrentNG: rt-metainfo"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true
tracing.workspace = true
sha1.workspace = true
sha2.workspace = true
hex.workspace = true
url.workspace = true
rt-bencode = { path = "../rt-bencode" }
rt-path = { path = "../rt-path" }
