#!/bin/sh
set -e

case "$1" in
    configure)
        if ! getent group torrentngd >/dev/null; then
            addgroup --system torrentngd
        fi
        if ! getent passwd torrentngd >/dev/null; then
            adduser --system --ingroup torrentngd \
                --home /var/lib/torrentngd --no-create-home \
                --shell /usr/sbin/nologin torrentngd
        fi
        ;;
esac

#DEBHELPER#
