d /var/lib/rtorrent 0750 rtorrent rtorrent -
d /var/lib/rtorrent/downloads 0750 rtorrent rtorrent -
d /var/lib/rtorrent/session 0750 rtorrent rtorrent -
d /var/lib/torrentng 0750 rtorrent rtorrent -
d /etc/rtorrent 0750 root rtorrent -
d /etc/torrentng 0750 root rtorrent -
