[package]
name = "rt-api-native"
description = "TorrentNG: axum REST API server (native JSON endpoints)"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
axum.workspace = true
base64.workspace = true
tokio.workspace = true
tower.workspace = true
futures.workspace = true
rt-api-model = { path = "../rt-api-model" }
rt-engine = { path = "../rt-engine" }
rt-metainfo = { path = "../rt-metainfo" }
rt-session = { path = "../rt-session" }
rt-storage = { path = "../rt-storage" }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
tower.workspace = true
