[package]
name = "rt-piece-map"
description = "rtorrentNG: rt-piece-map"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true
tracing.workspace = true
rt-path = { path = "../rt-path" }

[dev-dependencies]
proptest.workspace = true
