[package]
name = "rt-peer-wire"
description = "TorrentNG: BEP 3 peer wire protocol codec"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
bytes.workspace = true
rt-bencode = { path = "../rt-bencode" }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
